### ISSUE TITLE
Python dependencies

### ISSUE THREAD

**Issue by Xiaoli-W** [JmfanBU/DRIBO#1]
Can you provide the versions of Python dependencies? I am defeated when configuring the environment.

**Comment by JmfanBU** [comment]
Here are versions for some key dependencies we have tested on:
- torch - 1.10.1
- numpy - 1.19.5
- scikit-video - 1.1.11
- opencv-python - 4.0.0.21
- dm-control - 0.0.322773188.

Do you mind providing more details about the dependency issues? It would be helpful to locate the problem : )
